name: Deploy Part 5 - MapReduce CLI Method

on:
  push:
    branches: ["main"]
    paths:
      - '5_mapreduce/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D3F40D434C774005B6DBDD4E2DD961C1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FB081BA779914157A5A5CA5CFFA74AA8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_016E6A8B38B548DCBC05344617179A9F }}

      - name: 'Install dependencies and Zip'
        run: |
          cd 5_mapreduce
          python -m pip install --target="./.python_packages/lib/site-packages" -r requirements.txt
          zip -r ../deploy_mr.zip .

      - name: 'Deploy via Azure CLI'
        run: |
          az functionapp deployment source config-zip \
            --name lab2-functions-alice-mr-final \
            --resource-group lab2-AliceB \
            --src deploy_mr.zip
